### ISSUE TITLE
Adding a class to a field using the class parameter

### ISSUE THREAD

**Issue by SolidDev** [bootsz/wp-advanced-search#134]
This is said to be included in the 1.1.1 release. I am on the latest version which I believe is 1.4. My field construct looks like this, but the output does not contain my defined class.

    $args['fields'][] = array(  
       'type' => 'meta_key',
       'label' => 'Architectural Enhancement Product Types',
       'format' => 'checkbox',
       'class' => 'product_types_group',
       'meta_key' => 'architectural_enhancement_product_types',
       'compare' => 'IN',
       'values' => array(  
          'Checkbox 1' => 'Checkbox 1',
          'Checkbox 2' => 'Checkbox 2',
          'Checkbox 3' => 'Checkbox 3',
       ), 
    );

**Comment by bootsz** [comment]
Looks like there was a mistake in the code for v1.4 where the class was getting added to each individual checkbox/radio input instead of the container div, which is the intended behavior.  I have fixed this issue.

**Comment by SolidDev** [comment]
Great. I was actually using the master version. I see your update in the 1.4 beta, but it's still not working in the master version.

**Comment by SolidDev** [comment]
I've forked the master and fixed the class parameter bug. I've also made sure the class is added to the parent div container, not the actual input element.

https://github.com/SolidDev/wp-advanced-search/commit/ffdc0175b757055cc9e568b4277e96a2ce617659

**Comment by bootsz** [comment]
I'm planning to replace master with the 1.4-beta branch fairly soon once I get the documentation finished so I may not get around to fixing this in the v1.3 code.  Thanks for posting your solution though so others can get it if needed.
